### ISSUE TITLE
GetAcls from AivenAclAuthorizer

### ISSUE THREAD

**Issue by sderosiaux** [aiven/auth-for-apache-kafka#2]
Hi,

First, thanks for your great platform!

I want to use some third-party tools to manage my clusters hosted in Aiven.
Unfortunately, the brokers at Aiven don't return the current ACLs (because the AivenAclAuthorizer don't do it). Who are the principals (User: and ServiceUser:), their permissions etc.
Is it planned to do it? I'm just talking about the gets, not the creating/deleting methods.

Thanks

**Comment by ivanyu** [comment]
Hi Stéphane,

I'm terribly sorry for the late reply!
This sounds like an useful feature. We'll need to think a little how to convert our regex-based ACLs with narrow ACLs expected by Kafka.

**Comment by weeco** [comment]
Hey @ivanyu , any update on this?
We'd like to make [Kowl](https://github.com/cloudhut/kowl) fully compatible with Aiven as well, but as described by Stéphane the API request fails because the getAcls() method is not yet implemented in the authorizer.

I assume there's no workaround for third party software either right?

**Comment by ivanyu** [comment]
Thanks to #111, the authorizer now makes the best effort attempt to return parse the ACL definitions from the regex form into the Kafka form and return them when requested.

**Comment by jeqo** [comment]
Closing, as solved by #111 -- let us know we are missing anything here, thanks!
